# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-30 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='phone',
            field=models.CharField(default='', max_length=254),
        ),
    ]
