# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-02 11:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_remove_contact_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='from_email',
        ),
    ]
