# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-02 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_remove_contact_from_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='your_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
