# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-30 13:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_auto_20200327_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL),
        ),
    ]
