# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-08 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_auto_20200330_1358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='country',
            new_name='address_line_1',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='street_address1',
            new_name='address_line_2',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='postcode',
            new_name='eircode',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='full_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='street_address2',
            new_name='town',
        ),
        migrations.RemoveField(
            model_name='order',
            name='town_or_city',
        ),
        migrations.AddField(
            model_name='order',
            name='email_address',
            field=models.EmailField(default=1, max_length=254),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(max_length=25),
        ),
    ]
