# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-08 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_auto_20200408_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='email_address',
            field=models.EmailField(max_length=254),
        ),
    ]
